window.RIIZE_EVENTS = [
  // ===== 2023年（出道年） =====
  {
    id: 1,
    title: "RIIZE 出道 Showcase 'RIIZING DAY: RIIZE Premiere'",
    type: "concert",
    typeLabel: "出道Showcase",
    date: "2023-09-04",
    time: "18:00",
    city: "首尔",
    venue: "Blue Square Mastercard厅",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZE 正式出道 Showcase，首次公开《Get A Guitar》和《Memories》舞台，与全球粉丝见面。",
    highlight: "出道日！首张单曲专辑《Get A Guitar》发行"
  },
  {
    id: 2,
    title: "SMTOWN LIVE 2023 : SMCU Palace @ Jakarta",
    type: "festival",
    typeLabel: "家族演唱会",
    date: "2023-09-23",
    time: "18:00",
    city: "雅加达",
    venue: "GBK 主体育场",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "IDR",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.smtown.com/",
    desc: "SMTOWN 家族演唱会雅加达站，RIIZE 出道后首次参加家族演唱会。",
    highlight: "出道后首次家族演唱会"
  },
  {
    id: 3,
    title: "KCON SAUDI ARABIA 2023",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2023-10-06",
    time: "20:00",
    city: "利雅得",
    venue: "Boulevard Riyadh City",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "SAR",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://www.kconofficial.com/",
    desc: "KCON 沙特阿拉伯站，RIIZE 首次出演 KCON。",
    highlight: "首次 KCON 舞台"
  },
  {
    id: 4,
    title: "2023 MAMA AWARDS",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2023-11-28",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://mama.mwave.me/",
    desc: "2023 MAMA 大奖，RIIZE 获得最受喜爱新人奖。",
    highlight: "获得最佳新人奖！"
  },
  {
    id: 5,
    title: "2023 Melon Music Awards (MMA)",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2023-12-02",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "Kakao Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "2023 MMA 颁奖典礼，RIIZE 获得年度新人奖。",
    highlight: "MMA 新人奖大赏！"
  },
  {
    id: 6,
    title: "第33届首尔歌谣大赏",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2024-01-02",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "首尔体育",
    ticketUrl: "https://www.seoulmusicawards.com/",
    desc: "第33届首尔歌谣大赏，RIIZE 获得本赏和新人奖。",
    highlight: "本赏 + 新人奖双丰收"
  },

  // ===== 2024年 =====
  {
    id: 7,
    title: "2024 RIIZE FAN-CON TOUR 'RIIZING DAY' 首尔站 Day1",
    type: "concert",
    typeLabel: "Fan-Con",
    date: "2024-05-04",
    time: "17:00",
    city: "首尔",
    venue: "蚕室室内体育馆",
    status: "ended",
    statusLabel: "已结束",
    price: "154,000",
    currency: "KRW",
    priceCNY: "816",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZE 首次 Fan-Con 巡演首尔站，'RIIZING DAY' 主题。",
    highlight: "首次 Fan-Con 巡演！"
  },
  {
    id: 8,
    title: "2024 RIIZE FAN-CON TOUR 'RIIZING DAY' 首尔站 Day2",
    type: "concert",
    typeLabel: "Fan-Con",
    date: "2024-05-05",
    time: "17:00",
    city: "首尔",
    venue: "蚕室室内体育馆",
    status: "ended",
    statusLabel: "已结束",
    price: "154,000",
    currency: "KRW",
    priceCNY: "816",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZE 首次 Fan-Con 巡演首尔站第二天。",
    highlight: "首尔两场连开"
  },
  {
    id: 9,
    title: "2024 RIIZE FAN-CON 'RIIZING DAY' 东京站 Day1",
    type: "concert",
    typeLabel: "Fan-Con",
    date: "2024-05-11",
    time: "17:00",
    city: "东京",
    venue: "国立代代木竞技场第一体育馆",
    status: "ended",
    statusLabel: "已结束",
    price: "12,800",
    currency: "JPY",
    priceCNY: "602",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZE 首次日本 Fan-Con，东京站两场连开。",
    highlight: "日本首演！"
  },
  {
    id: 10,
    title: "2024 RIIZE FAN-CON 'RIIZING DAY' 东京站 Day2",
    type: "concert",
    typeLabel: "Fan-Con",
    date: "2024-05-12",
    time: "17:00",
    city: "东京",
    venue: "国立代代木竞技场第一体育馆",
    status: "ended",
    statusLabel: "已结束",
    price: "12,800",
    currency: "JPY",
    priceCNY: "602",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZE 首次日本 Fan-Con 东京站第二天。",
    highlight: "东京两场连开"
  },
  {
    id: 11,
    title: "2024 RIIZE FAN-CON 'RIIZING DAY' 香港站",
    type: "concert",
    typeLabel: "Fan-Con",
    date: "2024-06-01",
    time: "19:00",
    city: "香港",
    venue: "亚洲国际博览馆",
    status: "ended",
    statusLabel: "已结束",
    price: "1,280",
    currency: "HKD",
    priceCNY: "1,178",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZE 首次香港 Fan-Con。",
    highlight: "香港首秀！"
  },
  {
    id: 12,
    title: "2024 RIIZE FAN-CON 'RIIZING DAY' 台北站",
    type: "concert",
    typeLabel: "Fan-Con",
    date: "2024-06-15",
    time: "18:00",
    city: "台北",
    venue: "新北市工商展览中心",
    status: "ended",
    statusLabel: "已结束",
    price: "4,800",
    currency: "TWD",
    priceCNY: "1,100",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZE 首次台湾 Fan-Con。",
    highlight: "台湾首秀！"
  },
  {
    id: 13,
    title: "SUMMER SONIC 2024 东京",
    type: "festival",
    typeLabel: "音乐节",
    date: "2024-08-17",
    time: "14:00",
    city: "东京",
    venue: "幕张展览馆",
    status: "ended",
    statusLabel: "已结束",
    price: "19,800",
    currency: "JPY",
    priceCNY: "931",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SUMMER SONIC",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "日本最大夏季音乐节 SUMMER SONIC 2024。",
    highlight: "首次 SUMMER SONIC！"
  },
  {
    id: 14,
    title: "RIIZE 出道 1周年 Fan Party 'RIIZE 1000 DAYS'",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2024-09-04",
    time: "19:00",
    city: "首尔",
    venue: "在线 + 线下",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZE 出道 1000 天特别粉丝派对。",
    highlight: "出道 1000 天纪念！"
  },
  {
    id: 15,
    title: "2024 MAMA AWARDS",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2024-11-22",
    time: "17:00",
    city: "大阪",
    venue: "京瓷巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "2024 MAMA 大奖大阪站。",
    highlight: "MAMA 舞台"
  },

  // ===== 2025年 =====
  {
    id: 16,
    title: "RIIZE JAPAN FANMEETING 2025 'The Secret LIEZ' 横滨 Day1",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2025-01-18",
    time: "17:00",
    city: "横滨",
    venue: "Pia Arena MM",
    status: "ended",
    statusLabel: "已结束",
    price: "10,800",
    currency: "JPY",
    priceCNY: "508",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZE 日本首次粉丝俱乐部专属 FM，'The Secret LIEZ' 主题。",
    highlight: "日本 FC 限定 FM！"
  },
  {
    id: 17,
    title: "RIIZE JAPAN FANMEETING 2025 'The Secret LIEZ' 横滨 Day2",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2025-01-19",
    time: "17:00",
    city: "横滨",
    venue: "Pia Arena MM",
    status: "ended",
    statusLabel: "已结束",
    price: "10,800",
    currency: "JPY",
    priceCNY: "508",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZE 日本首次粉丝俱乐部专属 FM 第二天。",
    highlight: "横滨两场连开"
  },
  {
    id: 18,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 首尔站 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-07-04",
    time: "19:00",
    city: "首尔",
    venue: "KSPO DOME",
    status: "ended",
    statusLabel: "已结束",
    price: "154,000",
    currency: "KRW",
    priceCNY: "816",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZE 首次世界巡演 [RIIZING LOUD] 首尔站。",
    highlight: "首次世界巡演！首尔三场连开"
  },
  {
    id: 19,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 首尔站 Day2",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-07-05",
    time: "19:00",
    city: "首尔",
    venue: "KSPO DOME",
    status: "ended",
    statusLabel: "已结束",
    price: "154,000",
    currency: "KRW",
    priceCNY: "816",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZE 首次世界巡演 [RIIZING LOUD] 首尔站第二天。",
    highlight: "首尔三场连开"
  },
  {
    id: 20,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 首尔站 Day3",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-07-06",
    time: "17:00",
    city: "首尔",
    venue: "KSPO DOME",
    status: "ended",
    statusLabel: "已结束",
    price: "154,000",
    currency: "KRW",
    priceCNY: "816",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZE 首次世界巡演 [RIIZING LOUD] 首尔站第三天。",
    highlight: "首尔三场连开"
  },
  {
    id: 21,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 神户站 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-07-12",
    time: "17:00",
    city: "神户",
    venue: "GLION ARENA KOBE",
    status: "ended",
    statusLabel: "已结束",
    price: "14,800",
    currency: "JPY",
    priceCNY: "696",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD 世界巡演日本神户站。",
    highlight: "日本巡演第一站"
  },
  {
    id: 22,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 神户站 Day2",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-07-13",
    time: "17:00",
    city: "神户",
    venue: "GLION ARENA KOBE",
    status: "ended",
    statusLabel: "已结束",
    price: "14,800",
    currency: "JPY",
    priceCNY: "696",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD 世界巡演日本神户站第二天。",
    highlight: "神户两场连开"
  },
  {
    id: 23,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 香港站",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-07-19",
    time: "19:00",
    city: "香港",
    venue: "亚洲国际博览馆",
    status: "ended",
    statusLabel: "已结束",
    price: "1,680",
    currency: "HKD",
    priceCNY: "1,546",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演香港站。",
    highlight: "香港演唱会"
  },
  {
    id: 24,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 埼玉站 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-07-23",
    time: "18:00",
    city: "埼玉",
    venue: "埼玉超级竞技场",
    status: "ended",
    statusLabel: "已结束",
    price: "14,800",
    currency: "JPY",
    priceCNY: "696",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD 世界巡演日本埼玉站。",
    highlight: "埼玉超级竞技场"
  },
  {
    id: 25,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 埼玉站 Day2",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-07-24",
    time: "17:00",
    city: "埼玉",
    venue: "埼玉超级竞技场",
    status: "ended",
    statusLabel: "已结束",
    price: "14,800",
    currency: "JPY",
    priceCNY: "696",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD 世界巡演日本埼玉站第二天。",
    highlight: "埼玉两场连开"
  },
  {
    id: 26,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 广岛站 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-08-09",
    time: "17:00",
    city: "广岛",
    venue: "HIROSHIMA GREEN ARENA",
    status: "ended",
    statusLabel: "已结束",
    price: "14,800",
    currency: "JPY",
    priceCNY: "696",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD 世界巡演日本广岛站。",
    highlight: "广岛 Green Arena"
  },
  {
    id: 27,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 广岛站 Day2",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-08-10",
    time: "17:00",
    city: "广岛",
    venue: "HIROSHIMA GREEN ARENA",
    status: "ended",
    statusLabel: "已结束",
    price: "14,800",
    currency: "JPY",
    priceCNY: "696",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD 世界巡演日本广岛站第二天。",
    highlight: "广岛两场连开"
  },
  {
    id: 28,
    title: "SMTOWN LIVE 2025 in TOKYO Day1",
    type: "festival",
    typeLabel: "家族演唱会",
    date: "2025-08-16",
    time: "17:00",
    city: "东京",
    venue: "东京巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "15,800",
    currency: "JPY",
    priceCNY: "743",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "SMTOWN LIVE 2025 东京巨蛋站。",
    highlight: "东京巨蛋！"
  },
  {
    id: 29,
    title: "SMTOWN LIVE 2025 in TOKYO Day2",
    type: "festival",
    typeLabel: "家族演唱会",
    date: "2025-08-17",
    time: "16:00",
    city: "东京",
    venue: "东京巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "15,800",
    currency: "JPY",
    priceCNY: "743",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "SMTOWN LIVE 2025 东京巨蛋站第二天。",
    highlight: "东京巨蛋两场连开"
  },
  {
    id: 30,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 吉隆坡站",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-08-16",
    time: "19:00",
    city: "吉隆坡",
    venue: "Axiata Arena",
    status: "ended",
    statusLabel: "已结束",
    price: "688",
    currency: "MYR",
    priceCNY: "1,090",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演马来西亚吉隆坡站。",
    highlight: "马来西亚首秀！"
  },
  {
    id: 31,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 福冈站 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-08-23",
    time: "18:00",
    city: "福冈",
    venue: "福冈海洋展览馆",
    status: "ended",
    statusLabel: "已结束",
    price: "14,800",
    currency: "JPY",
    priceCNY: "696",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD 世界巡演日本福冈站。",
    highlight: "福冈 Marine Messe"
  },
  {
    id: 32,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 福冈站 Day2",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-08-24",
    time: "17:00",
    city: "福冈",
    venue: "福冈海洋展览馆",
    status: "ended",
    statusLabel: "已结束",
    price: "14,800",
    currency: "JPY",
    priceCNY: "696",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD 世界巡演日本福冈站第二天。",
    highlight: "福冈两场连开"
  },
  {
    id: 33,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 台北站",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-08-30",
    time: "19:00",
    city: "台北",
    venue: "台北小巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "5,200",
    currency: "TWD",
    priceCNY: "1,192",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演台北站。",
    highlight: "台北小巨蛋！"
  },
  {
    id: 34,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 曼谷站 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-09-13",
    time: "19:00",
    city: "曼谷",
    venue: "Impact Arena",
    status: "ended",
    statusLabel: "已结束",
    price: "5,800",
    currency: "THB",
    priceCNY: "1,160",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演泰国曼谷站。",
    highlight: "泰国首秀！"
  },
  {
    id: 35,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 曼谷站 Day2",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-09-14",
    time: "17:00",
    city: "曼谷",
    venue: "Impact Arena",
    status: "ended",
    statusLabel: "已结束",
    price: "5,800",
    currency: "THB",
    priceCNY: "1,160",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演泰国曼谷站第二天。",
    highlight: "曼谷两场连开"
  },
  {
    id: 36,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 洛杉矶站",
    type: "concert",
    typeLabel: "演唱会",
    date: "2025-11-11",
    time: "20:00",
    city: "洛杉矶",
    venue: "Kia Forum",
    status: "ended",
    statusLabel: "已结束",
    price: "199",
    currency: "USD",
    priceCNY: "1,433",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / AEG Presents",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演北美洛杉矶站。",
    highlight: "北美巡演！"
  },
  {
    id: 37,
    title: "2025 MAMA AWARDS",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2025-11-29",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://mama.mwave.me/",
    desc: "2025 MAMA 大奖，RIIZE 获得最佳男子组合奖。",
    highlight: "最佳男子组合！"
  },
  {
    id: 38,
    title: "2025 Melon Music Awards (MMA)",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2025-12-02",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "Kakao Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "2025 MMA，RIIZE 获得最佳男艺人表演奖、TOP10、百万销量 TOP10 三项大奖。",
    highlight: "MMA 三项大奖！"
  },

  // ===== 2026年 =====
  {
    id: 39,
    title: "2025 RIIZE CONCERT TOUR [RIIZING LOUD] 雅加达站",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-01-10",
    time: "19:00",
    city: "雅加达",
    venue: "ICE BSD Hall 5-6",
    status: "ended",
    statusLabel: "已结束",
    price: "2,800,000",
    currency: "IDR",
    priceCNY: "1,344",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演印尼雅加达站。",
    highlight: "印尼首秀！"
  },
  {
    id: 40,
    title: "第40届韩国金唱片奖",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-01-10",
    time: "17:00",
    city: "大阪",
    venue: "京瓷巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "金唱片奖委员会",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "第40届金唱片奖，RIIZE 获得最佳专辑奖。",
    highlight: "金唱片最佳专辑！"
  },
  {
    id: 41,
    title: "2026 RIIZE CONCERT TOUR [RIIZING LOUD] 马尼拉站",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-01-17",
    time: "19:00",
    city: "马尼拉",
    venue: "SM Mall of Asia Arena",
    status: "ended",
    statusLabel: "已结束",
    price: "8,500",
    currency: "PHP",
    priceCNY: "1,088",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / iMe",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演菲律宾马尼拉站。",
    highlight: "菲律宾首秀！"
  },
  {
    id: 42,
    title: "2026 RIIZE CONCERT TOUR [RIIZING LOUD] 新加坡站",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-01-24",
    time: "19:00",
    city: "新加坡",
    venue: "Singapore Indoor Stadium",
    status: "ended",
    statusLabel: "已结束",
    price: "348",
    currency: "SGD",
    priceCNY: "1,879",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / iMe",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演新加坡站。",
    highlight: "新加坡首秀！"
  },
  {
    id: 43,
    title: "SMTOWN LIVE 2025-26 in BANGKOK",
    type: "festival",
    typeLabel: "家族演唱会",
    date: "2026-02-14",
    time: "18:00",
    city: "曼谷",
    venue: "Rajamangala 国家体育场",
    status: "ended",
    statusLabel: "已结束",
    price: "4,800",
    currency: "THB",
    priceCNY: "960",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.smtown.com/",
    desc: "SMTOWN LIVE 曼谷站，情人节特别场。",
    highlight: "情人节 SMTOWN！"
  },
  {
    id: 44,
    title: "2026 RIIZE CONCERT TOUR [RIIZING LOUD] 澳门站 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-02-07",
    time: "19:00",
    city: "澳门",
    venue: "银河综艺馆",
    status: "ended",
    statusLabel: "已结束",
    price: "1,999",
    currency: "MOP",
    priceCNY: "1,819",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / 银河综艺馆",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演澳门站第一天。",
    highlight: "澳门首秀！两场连开"
  },
  {
    id: 45,
    title: "2026 RIIZE CONCERT TOUR [RIIZING LOUD] 澳门站 Day2（加场）",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-02-08",
    time: "19:00",
    city: "澳门",
    venue: "银河综艺馆",
    status: "ended",
    statusLabel: "已结束",
    price: "1,999",
    currency: "MOP",
    priceCNY: "1,819",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / 银河综艺馆",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演澳门站第二天（加场）。",
    highlight: "澳门加场！两场连开"
  },
  {
    id: 46,
    title: "RIIZING LOUD Special Edition 东京巨蛋 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-02-21",
    time: "18:00",
    city: "东京",
    venue: "东京巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "21,800",
    currency: "JPY",
    priceCNY: "1,025",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD Special Edition 东京巨蛋特别场第一天。",
    highlight: "东京巨蛋！三场连开"
  },
  {
    id: 47,
    title: "RIIZING LOUD Special Edition 东京巨蛋 Day2",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-02-22",
    time: "17:00",
    city: "东京",
    venue: "东京巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "21,800",
    currency: "JPY",
    priceCNY: "1,025",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD Special Edition 东京巨蛋特别场第二天。",
    highlight: "东京巨蛋！三场连开"
  },
  {
    id: 48,
    title: "RIIZING LOUD Special Edition 东京巨蛋 Day3（加场）",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-02-23",
    time: "16:00",
    city: "东京",
    venue: "东京巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "21,800",
    currency: "JPY",
    priceCNY: "1,025",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZING LOUD Special Edition 东京巨蛋特别场第三天（加场）。",
    highlight: "东京巨蛋加场！三场连开"
  },
  {
    id: 49,
    title: "RIIZING LOUD FINALE 首尔站 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-03-06",
    time: "19:00",
    city: "首尔",
    venue: "KSPO DOME",
    status: "ended",
    statusLabel: "已结束",
    price: "198,000",
    currency: "KRW",
    priceCNY: "1,049",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演 FINALE 首尔安可场第一天。",
    highlight: "巡演FINALE！首尔三场连开"
  },
  {
    id: 50,
    title: "RIIZING LOUD FINALE 首尔站 Day2",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-03-07",
    time: "19:00",
    city: "首尔",
    venue: "KSPO DOME",
    status: "ended",
    statusLabel: "已结束",
    price: "198,000",
    currency: "KRW",
    priceCNY: "1,049",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演 FINALE 首尔安可场第二天。",
    highlight: "巡演FINALE！首尔三场连开"
  },
  {
    id: 51,
    title: "RIIZING LOUD FINALE 首尔站 Day3",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-03-08",
    time: "17:00",
    city: "首尔",
    venue: "KSPO DOME",
    status: "ended",
    statusLabel: "已结束",
    price: "198,000",
    currency: "KRW",
    priceCNY: "1,049",
    ticketPlatform: "Melon Ticket / Interpark / Yes24 / NOL",
    ticketTime: "【会员先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://www.melon.com/",
    desc: "RIIZING LOUD 世界巡演 FINALE 首尔安可场第三天。",
    highlight: "巡演FINALE！首尔三场连开"
  },
  {
    id: 52,
    title: "Lollapalooza ARGENTINA 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-03-14",
    time: "20:00",
    city: "布宜诺斯艾利斯",
    venue: "San Isidro 赛马场",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "ARS",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "Lollapalooza",
    ticketUrl: "https://www.lollapalooza.com/",
    desc: "RIIZE 首次出演 Lollapalooza 阿根廷站。",
    highlight: "南美首秀！Lollapalooza"
  },
  {
    id: 53,
    title: "Lollapalooza CHILE 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-03-15",
    time: "20:00",
    city: "圣地亚哥",
    venue: "Parque O'Higgins",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "CLP",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "Lollapalooza",
    ticketUrl: "https://www.lollapalooza.com/",
    desc: "RIIZE 首次出演 Lollapalooza 智利站。",
    highlight: "智利首秀！Lollapalooza"
  },
  {
    id: 54,
    title: "Lollapalooza BRAZIL 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-03-21",
    time: "21:00",
    city: "圣保罗",
    venue: "Interlagos 赛道",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "BRL",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "Lollapalooza",
    ticketUrl: "https://www.lollapalooza.com/",
    desc: "RIIZE 首次出演 Lollapalooza 巴西站。",
    highlight: "巴西首秀！Lollapalooza"
  },
  {
    id: 55,
    title: "K2O Songkran Music Festival 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-04-14",
    time: "18:00",
    city: "曼谷",
    venue: "曼谷市中心",
    status: "ended",
    statusLabel: "已结束",
    price: "3,500",
    currency: "THB",
    priceCNY: "700",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "K2O",
    ticketUrl: "https://world.nol.com/",
    desc: "泰国泼水节音乐节 K2O Songkran。",
    highlight: "泼水节音乐节！"
  },
  {
    id: 56,
    title: "The Performance 横滨 Day1",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-04-10",
    time: "18:00",
    city: "横滨",
    venue: "K-Arena 横滨",
    status: "ended",
    statusLabel: "已结束",
    price: "16,800",
    currency: "JPY",
    priceCNY: "790",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZE 日本特别演唱会 'The Performance' 横滨站第一天。",
    highlight: "日本特别演唱会！两场连开"
  },
  {
    id: 57,
    title: "The Performance 横滨 Day2",
    type: "concert",
    typeLabel: "演唱会",
    date: "2026-04-11",
    time: "17:00",
    city: "横滨",
    venue: "K-Arena 横滨",
    status: "ended",
    statusLabel: "已结束",
    price: "16,800",
    currency: "JPY",
    priceCNY: "790",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "RIIZE 日本特别演唱会 'The Performance' 横滨站第二天。",
    highlight: "日本特别演唱会！两场连开"
  },
  {
    id: 58,
    title: "微博国际娱乐盛典 2026",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-04-25",
    time: "19:00",
    city: "澳门",
    venue: "银河综艺馆",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "CNY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "微博",
    ticketUrl: "https://world.nol.com/",
    desc: "微博国际娱乐盛典，RIIZE 获得年度国际艺人奖。",
    highlight: "中国首秀！"
  },
  {
    id: 59,
    title: "Kstyle PARTY 2026 Day2",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2026-05-10",
    time: "17:00",
    city: "横滨",
    venue: "K-Arena 横滨",
    status: "ended",
    statusLabel: "已结束",
    price: "12,800",
    currency: "JPY",
    priceCNY: "602",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "Kstyle",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "Kstyle PARTY 2026 拼盘演唱会第二天。",
    highlight: "Kstyle PARTY！"
  },
  {
    id: 60,
    title: "Channel B 棒球音乐节 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-05-25",
    time: "18:00",
    city: "台北",
    venue: "天母棒球场",
    status: "ended",
    statusLabel: "已结束",
    price: "3,800",
    currency: "TWD",
    priceCNY: "870",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "Channel B",
    ticketUrl: "https://world.nol.com/",
    desc: "台湾 Channel B 棒球音乐节。",
    highlight: "台湾音乐节！"
  },
  {
    id: 61,
    title: "WATERBOMB 首尔 2026 Day1",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-07-25",
    time: "17:00",
    city: "高阳",
    venue: "KINTEX 国际展览中心",
    status: "ended",
    statusLabel: "已结束",
    price: "165,000",
    currency: "KRW",
    priceCNY: "874",
    ticketPlatform: "Melon Ticket / NOL / Ticket Link / Queens Smile",
    ticketTime: "【1st 早鸟】2025年9月30日 11:00 北京时间<br>【2nd 早鸟】2025年12月15日 13:00 北京时间<br>【一般售票】以官方公告为准",
    organizer: "WATERBOMB",
    ticketUrl: "https://waterbomb.co.kr/",
    desc: "韩国最大夏日音乐节 WATERBOMB 首尔站（高阳KINTEX）。",
    highlight: "水弹音乐节！"
  },
  {
    id: 62,
    title: "WATERBOMB 首尔 2026 Day2",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-07-26",
    time: "17:00",
    city: "高阳",
    venue: "KINTEX 国际展览中心",
    status: "ended",
    statusLabel: "已结束",
    price: "165,000",
    currency: "KRW",
    priceCNY: "874",
    ticketPlatform: "Melon Ticket / NOL / Ticket Link / Queens Smile",
    ticketTime: "【1st 早鸟】2025年9月30日 11:00 北京时间<br>【2nd 早鸟】2025年12月15日 13:00 北京时间<br>【一般售票】以官方公告为准",
    organizer: "WATERBOMB",
    ticketUrl: "https://waterbomb.co.kr/",
    desc: "韩国最大夏日音乐节 WATERBOMB 首尔站第二天（高阳KINTEX）。",
    highlight: "水弹音乐节！两场连开"
  },
  {
    id: 63,
    title: "TIMA 国际音乐大赏 Day2",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-08-23",
    time: "19:00",
    city: "香港",
    venue: "启德主场馆",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "HKD",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "TIMA",
    ticketUrl: "https://world.nol.com/",
    desc: "TIMA 国际音乐大赏香港站第二天。",
    highlight: "香港颁奖礼！"
  },
  {
    id: 64,
    title: "Spotify House Seoul 2026",
    type: "festival",
    typeLabel: "特别演出",
    date: "2026-09-19",
    time: "20:00",
    city: "首尔",
    venue: "首尔某场馆",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "邀请制",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "Spotify",
    ticketUrl: "https://world.nol.com/",
    desc: "Spotify House Seoul 特别演出，邀请制。",
    highlight: "Spotify 特别演出！"
  },
  {
    id: 65,
    title: "RIIZE 出道3周年粉丝见面会 'Ch. RIIZE : ON AIR' Day1",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2026-09-12",
    time: "16:00",
    city: "仁川",
    venue: "INSPIRE Arena（迎仕柏竞技场）",
    status: "upcoming",
    statusLabel: "已售罄",
    price: "121,000",
    currency: "KRW",
    priceCNY: "641",
    ticketPlatform: "NOL / Melon Ticket",
    ticketTime: "【FC预认证（韩本土）】7月20日 13:00 ~ 7月27日 22:59 北京时间<br>【FC预认证（全球）】7月20日 13:00 ~ 7月28日 22:59 北京时间<br>【FC先行（韩本土）】7月27日 19:00 ~ 22:59 北京时间<br>【FC先行（全球）】7月28日 19:00 ~ 22:59 北京时间<br>【轮椅席FC先行】7月27日 09:00 ~ 7月28日 16:59 北京时间<br>【一般售票】7月29日 19:00 起 北京时间<br>【轮椅席一般售票】7月29日 09:00 起 北京时间",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://world.nol.com/en/articles/85486922-78da-44c2-b695-c16e3edc2b51",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出道3周年特别粉丝见面会 'Ch. RIIZE : ON AIR'。",
    highlight: "出道3周年！INSPIRE Arena 两场连开"
  },
  {
    id: 66,
    title: "RIIZE 出道3周年粉丝见面会 'Ch. RIIZE : ON AIR' Day2",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2026-09-13",
    time: "16:00",
    city: "仁川",
    venue: "INSPIRE Arena（迎仕柏竞技场）",
    status: "upcoming",
    statusLabel: "已售罄",
    price: "121,000",
    currency: "KRW",
    priceCNY: "641",
    ticketPlatform: "NOL / Melon Ticket",
    ticketTime: "【FC预认证（韩本土）】7月20日 13:00 ~ 7月27日 22:59 北京时间<br>【FC预认证（全球）】7月20日 13:00 ~ 7月28日 22:59 北京时间<br>【FC先行（韩本土）】7月27日 19:00 ~ 22:59 北京时间<br>【FC先行（全球）】7月28日 19:00 ~ 22:59 北京时间<br>【轮椅席FC先行】7月27日 09:00 ~ 7月28日 16:59 北京时间<br>【一般售票】7月29日 19:00 起 北京时间<br>【轮椅席一般售票】7月29日 09:00 起 北京时间",
    organizer: "SM Entertainment / Dream Maker",
    ticketUrl: "https://world.nol.com/en/articles/85486922-78da-44c2-b695-c16e3edc2b51",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出道3周年特别粉丝见面会 'Ch. RIIZE : ON AIR' 第二天。",
    highlight: "出道3周年！INSPIRE Arena 两场连开"
  },
  {
    id: 67,
    title: "2026 MAMA AWARDS",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-11-28",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://mama.mwave.me/",
    desc: "2026 MAMA 大奖。",
    highlight: "MAMA 颁奖礼"
  },
  {
    id: 68,
    title: "2026 Melon Music Awards (MMA)",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-12-02",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "Kakao Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "2026 MMA 颁奖典礼。",
    highlight: "MMA 颁奖礼"
  },
  {
    id: 69,
    title: "SMTOWN LIVE 2026 in SEOUL Day1",
    type: "festival",
    typeLabel: "家族演唱会",
    date: "2026-12-25",
    time: "18:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "165,000",
    currency: "KRW",
    priceCNY: "874",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.smtown.com/",
    desc: "SMTOWN LIVE 2026 首尔站圣诞节特别场第一天。",
    highlight: "圣诞节 SMTOWN！"
  },
  {
    id: 70,
    title: "SMTOWN LIVE 2026 in SEOUL Day2",
    type: "festival",
    typeLabel: "家族演唱会",
    date: "2026-12-26",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "165,000",
    currency: "KRW",
    priceCNY: "874",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.smtown.com/",
    desc: "SMTOWN LIVE 2026 首尔站第二天。",
    highlight: "首尔两场连开"
  },
  {
    id: 70,
    title: "第36届金唱片奖 Day1",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2024-01-06",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "金唱片奖委员会",
    ticketUrl: "https://www.goldendiscawards.com/",
    desc: "第36届金唱片奖第一天，RIIZE 获得新人奖。",
    highlight: "金唱片新人奖！"
  },
  {
    id: 71,
    title: "第36届金唱片奖 Day2",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2024-01-07",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "金唱片奖委员会",
    ticketUrl: "https://www.goldendiscawards.com/",
    desc: "第36届金唱片奖第二天。",
    highlight: "金唱片颁奖礼"
  },
  {
    id: 72,
    title: "Circle Chart Music Awards 2024",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2024-01-10",
    time: "18:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "Circle Chart",
    ticketUrl: "https://circlechart.kr/",
    desc: "Circle Chart 音乐奖，RIIZE 获得年度新人奖。",
    highlight: "Circle Chart 新人奖！"
  },
  {
    id: 73,
    title: "KCON LA 2024 Day1",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2024-07-26",
    time: "20:00",
    city: "洛杉矶",
    venue: "Crypto.com Arena",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "USD",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://www.kconofficial.com/",
    desc: "KCON LA 2024 第一天，RIIZE 首次出演 KCON 美国站。",
    highlight: "美国 KCON 首秀！"
  },
  {
    id: 74,
    title: "KCON LA 2024 Day2",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2024-07-27",
    time: "20:00",
    city: "洛杉矶",
    venue: "Crypto.com Arena",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "USD",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://www.kconofficial.com/",
    desc: "KCON LA 2024 第二天。",
    highlight: "KCON LA 两场连开"
  },
  {
    id: 75,
    title: "Music Bank in Mexico 2024",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2024-10-19",
    time: "20:00",
    city: "墨西哥城",
    venue: "Palacio de los Deportes",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "MXN",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "KBS",
    ticketUrl: "https://world.nol.com/",
    desc: "Music Bank 墨西哥站，RIIZE 首次出演。",
    highlight: "墨西哥首秀！"
  },
  {
    id: 76,
    title: "2024 MMA Melon Music Awards",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2024-11-30",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "Kakao Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "2024 MMA 颁奖典礼，RIIZE 获得 TOP10 本赏。",
    highlight: "MMA TOP10 本赏！"
  },
  {
    id: 77,
    title: "SBS 歌谣大战 2024",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2024-12-25",
    time: "18:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "SBS",
    ticketUrl: "https://www.sbs.co.kr/",
    desc: "SBS 歌谣大战 2024 圣诞节特别场。",
    highlight: "圣诞节 SBS 歌谣大战"
  },
  {
    id: 78,
    title: "MBC 歌谣大祭典 2024",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2024-12-31",
    time: "20:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "MBC",
    ticketUrl: "https://www.sbs.co.kr/",
    desc: "MBC 歌谣大祭典 2024 跨年场。",
    highlight: "跨年 MBC 歌谣大祭典"
  },
  {
    id: 79,
    title: "Golden Disc Awards 2025 Day1",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2025-01-04",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "金唱片奖委员会",
    ticketUrl: "https://www.goldendiscawards.com/",
    desc: "第37届金唱片奖第一天，RIIZE 获得本赏。",
    highlight: "金唱片本赏！"
  },
  {
    id: 80,
    title: "Golden Disc Awards 2025 Day2",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2025-01-05",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "金唱片奖委员会",
    ticketUrl: "https://www.goldendiscawards.com/",
    desc: "第37届金唱片奖第二天。",
    highlight: "金唱片颁奖礼"
  },
  {
    id: 81,
    title: "Circle Chart Music Awards 2025",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2025-01-15",
    time: "18:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "Circle Chart",
    ticketUrl: "https://circlechart.kr/",
    desc: "Circle Chart 音乐奖 2025，RIIZE 获得年度艺人奖。",
    highlight: "Circle Chart 年度艺人！"
  },
  {
    id: 82,
    title: "SMTOWN LIVE 2025 in HONG KONG Day1",
    type: "festival",
    typeLabel: "家族演唱会",
    date: "2025-03-08",
    time: "18:00",
    city: "香港",
    venue: "启德主场馆",
    status: "ended",
    statusLabel: "已结束",
    price: "1,880",
    currency: "HKD",
    priceCNY: "1,730",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.smtown.com/",
    desc: "SMTOWN LIVE 2025 香港站第一天。",
    highlight: "香港 SMTOWN！两场连开"
  },
  {
    id: 83,
    title: "SMTOWN LIVE 2025 in HONG KONG Day2",
    type: "festival",
    typeLabel: "家族演唱会",
    date: "2025-03-09",
    time: "17:00",
    city: "香港",
    venue: "启德主场馆",
    status: "ended",
    statusLabel: "已结束",
    price: "1,880",
    currency: "HKD",
    priceCNY: "1,730",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://www.smtown.com/",
    desc: "SMTOWN LIVE 2025 香港站第二天。",
    highlight: "香港两场连开"
  },
  {
    id: 84,
    title: "KCON JAPAN 2025 Day1",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2025-05-10",
    time: "17:00",
    city: "千叶",
    venue: "幕张展览馆",
    status: "ended",
    statusLabel: "已结束",
    price: "16,800",
    currency: "JPY",
    priceCNY: "790",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "KCON JAPAN 2025 第一天。",
    highlight: "KCON 日本站！"
  },
  {
    id: 85,
    title: "KCON JAPAN 2025 Day2",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2025-05-11",
    time: "17:00",
    city: "千叶",
    venue: "幕张展览馆",
    status: "ended",
    statusLabel: "已结束",
    price: "16,800",
    currency: "JPY",
    priceCNY: "790",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "KCON JAPAN 2025 第二天。",
    highlight: "KCON 两场连开"
  },
  {
    id: 86,
    title: "WATERBOMB 东京 2025",
    type: "festival",
    typeLabel: "音乐节",
    date: "2025-07-27",
    time: "16:00",
    city: "东京",
    venue: "东京味之素体育场",
    status: "ended",
    statusLabel: "已结束",
    price: "18,800",
    currency: "JPY",
    priceCNY: "884",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "WATERBOMB",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "WATERBOMB 东京站，RIIZE 首次出演日本水弹音乐节。",
    highlight: "日本水弹音乐节首秀！"
  },
  {
    id: 87,
    title: "KCON LA 2025 Day1",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2025-08-09",
    time: "20:00",
    city: "洛杉矶",
    venue: "Crypto.com Arena",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "USD",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://www.kconofficial.com/",
    desc: "KCON LA 2025 第一天。",
    highlight: "KCON LA！"
  },
  {
    id: 88,
    title: "KCON LA 2025 Day2",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2025-08-10",
    time: "20:00",
    city: "洛杉矶",
    venue: "Crypto.com Arena",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "USD",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://www.kconofficial.com/",
    desc: "KCON LA 2025 第二天。",
    highlight: "KCON LA 两场连开"
  },
  {
    id: 89,
    title: "2025 MMA Melon Music Awards",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2025-11-29",
    time: "17:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "Kakao Entertainment",
    ticketUrl: "https://www.melon.com/",
    desc: "2025 MMA 颁奖典礼，RIIZE 获得年度艺人奖。",
    highlight: "MMA 年度艺人！"
  },
  {
    id: 90,
    title: "SBS 歌谣大战 2025",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2025-12-25",
    time: "18:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "SBS",
    ticketUrl: "https://www.sbs.co.kr/",
    desc: "SBS 歌谣大战 2025 圣诞节特别场。",
    highlight: "圣诞节 SBS 歌谣大战"
  },
  {
    id: 91,
    title: "MBC 歌谣大祭典 2025",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2025-12-31",
    time: "20:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "MBC",
    ticketUrl: "https://www.sbs.co.kr/",
    desc: "MBC 歌谣大祭典 2025 跨年场。",
    highlight: "跨年 MBC 歌谣大祭典"
  },
  {
    id: 92,
    title: "第38届金唱片奖 Day1",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-01-06",
    time: "17:00",
    city: "大阪",
    venue: "京瓷巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "金唱片奖委员会",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "第38届金唱片奖第一天，RIIZE 获得大赏。",
    highlight: "金唱片大赏！"
  },
  {
    id: 93,
    title: "第38届金唱片奖 Day2",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-01-07",
    time: "17:00",
    city: "大阪",
    venue: "京瓷巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "金唱片奖委员会",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "第38届金唱片奖第二天。",
    highlight: "金唱片颁奖礼"
  },
  {
    id: 94,
    title: "Circle Chart Music Awards 2026",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-01-15",
    time: "18:00",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "Circle Chart",
    ticketUrl: "https://circlechart.kr/",
    desc: "Circle Chart 音乐奖 2026，RIIZE 获得年度专辑奖。",
    highlight: "Circle Chart 年度专辑！"
  },
  {
    id: 95,
    title: "KCON JAPAN 2026 Day1",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2026-05-16",
    time: "17:00",
    city: "千叶",
    venue: "幕张展览馆",
    status: 'ended',
    statusLabel: '已结束',
    price: "17,800",
    currency: "JPY",
    priceCNY: "837",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "KCON JAPAN 2026 第一天。",
    highlight: "KCON 日本站！"
  },
  {
    id: 96,
    title: "KCON JAPAN 2026 Day2",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2026-05-17",
    time: "17:00",
    city: "千叶",
    venue: "幕张展览馆",
    status: 'ended',
    statusLabel: '已结束',
    price: "17,800",
    currency: "JPY",
    priceCNY: "837",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "CJ ENM",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "KCON JAPAN 2026 第二天。",
    highlight: "KCON 两场连开"
  },
  {
    id: 97,
    title: "WATERBOMB 首尔 2026 Day3",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-07-27",
    time: "17:00",
    city: "高阳",
    venue: "KINTEX 国际展览中心",
    status: 'ended',
    statusLabel: '已结束',
    price: "165,000",
    currency: "KRW",
    priceCNY: "874",
    ticketPlatform: "Melon Ticket / NOL / Ticket Link / Queens Smile",
    ticketTime: "【1st 早鸟】2025年9月30日 11:00 北京时间<br>【2nd 早鸟】2025年12月15日 13:00 北京时间<br>【一般售票】以官方公告为准",
    organizer: "WATERBOMB",
    ticketUrl: "https://waterbomb.co.kr/",
    desc: "WATERBOMB 首尔站第三天（高阳KINTEX）。",
    highlight: "水弹音乐节第三天"
  },
  {
    id: 98,
    title: "WATERBOMB 东京 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-08-02",
    time: "16:00",
    city: "东京",
    venue: "东京味之素体育场",
    status: 'ended',
    statusLabel: '已结束',
    price: "19,800",
    currency: "JPY",
    priceCNY: "931",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "WATERBOMB",
    ticketUrl: "https://riizeofficial.jp/",
    desc: "WATERBOMB 东京站 2026。",
    highlight: "日本水弹音乐节！"
  },
  {
    id: 99,
    title: "RIIZE POP-UP [ARCHIIVE²] 首尔快闪店",
    type: "popup",
    typeLabel: "快闪店",
    date: "2026-06-16",
    dateEnd: "2026-06-28",
    time: "12:00-20:00",
    city: "首尔",
    venue: "Layer Studio 11（麻浦区广城路41-11）",
    status: "ended",
    statusLabel: "已结束",
    price: "免费入场",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "NOL / Naver",
    ticketTime: "【FC先行预约】6月10日 / 6月16日<br>【一般预约】6月12日 20:00 北京时间",
    organizer: "SM Entertainment",
    ticketUrl: "https://world.nol.com/en/content/festas/019ea9e7-ffa1-70f0-91c0-a03509e9f3a0",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "纪念迷你二辑《II》发行的特别快闪店「ARCHIIVE²」，约250坪，100%预约制，全场次售罄。",
    highlight: "迷你二辑回归快闪！全场售罄"
  },
  {
    id: 100,
    title: "RIIZE POP-UP [ARCHIIVE²] 上海快闪店",
    type: "popup",
    typeLabel: "快闪店",
    date: "2026-07-30",
    dateEnd: "2026-08-09",
    time: "10:00-22:00",
    city: "上海",
    venue: "徐汇区衡山路932号",
    status: 'ended',
    statusLabel: '已结束',
    price: "免费入场",
    currency: "CNY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 快闪店「ARCHIIVE²」中国首站，登陆上海。",
    highlight: "中国首站快闪！"
  },
  {
    id: 101,
    title: 'RIIZE POP-UP STORE "All of You" 原宿快闪店',
    type: "popup",
    typeLabel: "快闪店",
    date: "2026-02-18",
    dateEnd: "2026-03-02",
    time: "11:00-20:00",
    city: "东京",
    venue: "UNIVERSAL MUSIC STORE HARAJUKU",
    status: "ended",
    statusLabel: "已结束",
    price: "免费入场",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "纪念日本第2张单曲《All of You》发行的快闪店，在原宿竹下通举办。",
    highlight: "日本二单快闪！"
  },
  {
    id: 102,
    title: "RAPBEAT Festival 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-06-20",
    time: "14:00",
    city: "首尔",
    venue: "麻浦区 Oil Tank Culture Park",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "RAPBEAT",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出演 RAPBEAT Festival 2026 第一天，与ZICO、Simon Dominic、NCT泰容等同台。",
    highlight: "回归期首个音乐节！"
  },
  {
    id: 103,
    title: "Busan One Asia Festival 2026 - PARK CONCERT",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-06-20",
    time: "18:00",
    city: "釜山",
    venue: "华明生态公园足球场",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "釜山广域市",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "釜山One Asia Festival（BOF）十周年纪念，户外公园演唱会。",
    highlight: "BOF十周年！"
  },
  {
    id: 104,
    title: "Busan One Asia Festival 2026 - BIG CONCERT Day1",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-06-27",
    time: "19:00",
    city: "釜山",
    venue: "釜山亚运会主体育场",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "釜山广域市",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "釜山One Asia Festival（BOF）十周年纪念大型演唱会第一天。",
    highlight: "BOF十周年大型演唱会"
  },
  {
    id: 105,
    title: "Busan One Asia Festival 2026 - BIG CONCERT Day2",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-06-28",
    time: "18:00",
    city: "釜山",
    venue: "釜山亚运会主体育场",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "釜山广域市",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "釜山One Asia Festival（BOF）十周年纪念大型演唱会第二天。",
    highlight: "BOF十周年两场连开"
  },
  {
    id: 106,
    title: "RIIZE 迷你二辑《II》香港签售会",
    type: "fansign",
    typeLabel: "签售会",
    date: "2026-08-28",
    time: "19:00",
    city: "香港",
    venue: "香港（地点另行通知）",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "HKD",
    priceCNY: "",
    ticketPlatform: "Fantopia",
    ticketTime: "【应募期间】7月23日 19:00 ~ 8月5日 23:59 北京时间",
    organizer: "SM Entertainment",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 迷你二辑《II》香港线下粉丝签名会，通过Fantopia购买专辑抽取名额。",
    highlight: "香港首次签售！"
  },
  {
    id: 107,
    title: "K-World Dream Awards 2026",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-09-19",
    time: "17:00",
    city: "高阳",
    venue: "以官方公告为准",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "K-World",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "2026 K-World Dream Awards，RIIZE 出席并表演。",
    highlight: "颁奖礼舞台"
  },
  {
    id: 108,
    title: "The Fact Music Awards 2026",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-09-20",
    time: "17:00",
    city: "釜山",
    venue: "以官方公告为准",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "The Fact",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "2026 The Fact Music Awards，RIIZE 出席并表演。",
    highlight: "TMA颁奖礼"
  },
  {
    id: 109,
    title: "FEST. INAZUMA 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-09-22",
    time: "12:00",
    city: "草津",
    venue: "滋贺县草津市",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【早鸟票】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "FEST. INAZUMA",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "日本大型户外音乐节 FEST. INAZUMA 2026，RIIZE 出演。",
    highlight: "日本音乐节"
  },
  {
    id: 110,
    title: "Inkigayo Live in Tokyo 2026",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2026-10-04",
    time: "17:00",
    city: "所泽",
    venue: "所泽航空纪念公园",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SBS / 日本电视台",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "SBS人气歌谣东京演唱会，RIIZE 出演。",
    highlight: "人气歌谣东京演唱会"
  },
  {
    id: 111,
    title: "SMTOWN LIVE 2025-26 in FUKUOKA Day1",
    type: "concert",
    typeLabel: "家族演唱会",
    date: "2026-01-31",
    time: "16:00",
    city: "福冈",
    venue: "福冈 PayPay Dome",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "SM娱乐创立30周年纪念SMTOWN LIVE福冈站，RIIZE首次参加日本SMTOWN。",
    highlight: "SM30周年！福冈SMTOWN"
  },
  {
    id: 112,
    title: "SMTOWN LIVE 2025-26 in FUKUOKA Day2",
    type: "concert",
    typeLabel: "家族演唱会",
    date: "2026-02-01",
    time: "15:00",
    city: "福冈",
    venue: "福冈 PayPay Dome",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC先行抽选】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "SM娱乐创立30周年纪念SMTOWN LIVE福冈站第二天。",
    highlight: "SMTOWN两场连开"
  },
  {
    id: 113,
    title: "The Performance 2026 横滨 Day1",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2026-04-10",
    time: "17:30",
    city: "横滨",
    venue: "K Arena 横滨",
    status: "ended",
    statusLabel: "已结束",
    price: "13,000",
    currency: "JPY",
    priceCNY: "610",
    ticketPlatform: "e+ / ぴあ",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "マイナビ",
    ticketUrl: "https://theperformance.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "RIIZE 与 THE RAMPAGE 同台的特别拼盘演唱会，首日有合作舞台。",
    highlight: "横滨K Arena！合作舞台"
  },
  {
    id: 114,
    title: "The Performance 2026 横滨 Day2",
    type: "festival",
    typeLabel: "拼盘演唱会",
    date: "2026-04-11",
    time: "16:00",
    city: "横滨",
    venue: "K Arena 横滨",
    status: "ended",
    statusLabel: "已结束",
    price: "14,000",
    currency: "JPY",
    priceCNY: "657",
    ticketPlatform: "e+ / ぴあ",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "マイナビ",
    ticketUrl: "https://theperformance.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "The Performance 2026 第二天，与ATEEZ、EVNNE等同台。",
    highlight: "横滨两场连开"
  },
  {
    id: 115,
    title: "2026 LOVESOME Festival",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-04-12",
    time: "19:30",
    city: "首尔",
    venue: "延世大学 露天剧场",
    status: "ended",
    statusLabel: "已结束",
    price: "110,000",
    currency: "KRW",
    priceCNY: "583",
    ticketPlatform: "NOL / Melon Ticket",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "LOVESOME",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "韩国春季代表性音乐节LOVESOME 2026，RIIZE出演。",
    highlight: "春季音乐节！"
  },
  {
    id: 116,
    title: "Channel B Baseball Music Fest 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-05-25",
    time: "15:00",
    city: "台北",
    venue: "台北巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "TWD",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "Channel B",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "台湾棒球音乐节，RIIZE出演并参加开球仪式。",
    highlight: "台湾首秀！开球仪式"
  },
  {
    id: 117,
    title: "RIIZE 1000 DAYS FAN PARTY [RIIZE OFFICE] 第一场",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2026-05-30",
    time: "12:00",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Weverse",
    ticketTime: "【FC先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出道1000天纪念粉丝派对「RIIZE OFFICE」第一场。",
    highlight: "1000天纪念！"
  },
  {
    id: 118,
    title: "RIIZE 1000 DAYS FAN PARTY [RIIZE OFFICE] 第二场",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2026-05-30",
    time: "17:00",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Weverse",
    ticketTime: "【FC先行】以官方公告为准<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出道1000天纪念粉丝派对「RIIZE OFFICE」第二场。",
    highlight: "1000天两场连开"
  },
  {
    id: 119,
    title: "ULSAN MUSIC FESTIVAL 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-06-15",
    time: "18:00",
    city: "蔚山",
    venue: "太和江国家庭园 River Stage",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Melon Ticket",
    ticketTime: "【一般售票】5月22日 19:00 北京时间",
    organizer: "蔚山广域市",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "蔚山音乐节，RIIZE出演。",
    highlight: "蔚山音乐节"
  },
  {
    id: 120,
    title: "MyK FESTA 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-06-26",
    time: "18:00",
    city: "高阳",
    venue: "KINTEX",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "MyK",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "MyK FESTA 2026，RIIZE与HIGHLIGHT、TREASURE等同台。",
    highlight: "高阳KINTEX"
  },
  {
    id: 121,
    title: "2026 高雄啤酒音乐节",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-07-05",
    time: "21:30",
    city: "高雄",
    venue: "高雄梦时代购物中心广场",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "TWD",
    priceCNY: "",
    ticketPlatform: "免费入场",
    ticketTime: "免费入场",
    organizer: "高雄市政府",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "第18届高雄啤酒音乐节，RIIZE压轴出演。",
    highlight: "台湾音乐节！压轴"
  },
  {
    id: 122,
    title: "RIIZE JAPAN FANMEETING 2026 RPG 福冈",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2026-07-10",
    time: "17:30",
    city: "福冈",
    venue: "Marine Messe福冈 B馆",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC最速先行抽选】4月21日起<br>【FC二次先行抽选】5月18日起<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "RIIZE 第二次日本粉丝见面会「RPG - RIIZE PLAYING GAME -」福冈站，全席售罄。",
    highlight: "日本二巡FM！RPG概念"
  },
  {
    id: 123,
    title: "RIIZE JAPAN FANMEETING 2026 RPG 东京 Day1",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2026-07-15",
    time: "17:00",
    city: "东京",
    venue: "国立代代木竞技场第一体育馆",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC最速先行抽选】4月21日起<br>【FC二次先行抽选】5月18日起<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "RIIZE 第二次日本粉丝见面会「RPG - RIIZE PLAYING GAME -」东京站第一天。",
    highlight: "东京代代木！"
  },
  {
    id: 124,
    title: "RIIZE JAPAN FANMEETING 2026 RPG 东京 Day2",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2026-07-16",
    time: "13:00",
    city: "东京",
    venue: "国立代代木竞技场第一体育馆",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC最速先行抽选】4月21日起<br>【FC二次先行抽选】5月18日起<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "RIIZE 第二次日本粉丝见面会「RPG - RIIZE PLAYING GAME -」东京站第二天。",
    highlight: "东京两场连开"
  },
  {
    id: 125,
    title: "RIIZE JAPAN FANMEETING 2026 RPG 兵库 Day1",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2026-07-23",
    time: "17:30",
    city: "神户",
    venue: "神户世界纪念馆",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC最速先行抽选】4月21日起<br>【FC二次先行抽选】5月18日起<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "RIIZE 第二次日本粉丝见面会「RPG - RIIZE PLAYING GAME -」兵库站第一天。",
    highlight: "兵库站！"
  },
  {
    id: 126,
    title: "RIIZE JAPAN FANMEETING 2026 RPG 兵库 Day2",
    type: "fanmeeting",
    typeLabel: "粉丝见面会",
    date: "2026-07-24",
    time: "13:00",
    city: "神户",
    venue: "神户世界纪念馆",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "【FC最速先行抽选】4月21日起<br>【FC二次先行抽选】5月18日起<br>【一般售票】以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "RIIZE 第二次日本粉丝见面会「RPG - RIIZE PLAYING GAME -」兵库站第二天，全6场全席售罄，动员约5万人。",
    highlight: "全6场售罄！5万人"
  },
  {
    id: 127,
    title: "Mezamashi WANGAN Festival 2026",
    type: "festival",
    typeLabel: "音乐节",
    date: "2026-08-13",
    time: "以官方为准",
    city: "东京",
    venue: "以官方公告为准",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "【一般售票】以官方公告为准",
    organizer: "富士电视台",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "日本电视台晨间节目《闹钟电视》主办的湾岸音乐节，RIIZE出演。",
    highlight: "日本湾岸音乐节"
  },
  {
    id: 128,
    title: "DYD Night at Namsan 南山塔户外公演",
    type: "festival",
    typeLabel: "特别公演",
    date: "2026-06-19",
    time: "20:00",
    city: "首尔",
    venue: "南山 N首尔塔 户外舞台",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费入场",
    ticketTime: "免费入场",
    organizer: "SM Entertainment / Billboard Korea",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》回归纪念特别公演「DYD Night at Namsan」，与Billboard Korea合作，在南山N首尔塔户外舞台举行。雨中公演，外墙点灯活动同步进行。",
    highlight: "南山塔雨中公演！回归纪念"
  },
  {
    id: 129,
    title: "LG双子队 开球式 + 特别公演",
    type: "festival",
    typeLabel: "特别公演",
    date: "2026-08-08",
    time: "比赛后",
    city: "首尔",
    venue: "蚕室棒球场",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "以官方公告为准",
    organizer: "LG Twins",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出席LG双子队主场比赛开球仪式，成灿投球、银硕击球，比赛结束后进行特别公演。",
    highlight: "蚕室棒球场！开球+公演"
  },
  {
    id: 130,
    title: "仁川大学校庆 2026",
    type: "festival",
    typeLabel: "校庆",
    date: "2026-05-08",
    time: "以官方为准",
    city: "仁川",
    venue: "仁川大学",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费入场",
    ticketTime: "免费入场",
    organizer: "仁川大学",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "仁川大学2026年大学校庆，RIIZE出演Day3。",
    highlight: "仁川大学校庆"
  },
  {
    id: 131,
    title: "西江大学校庆 2026",
    type: "festival",
    typeLabel: "校庆",
    date: "2026-05-14",
    time: "15:30",
    city: "首尔",
    venue: "西江大学",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费入场",
    ticketTime: "免费入场",
    organizer: "西江大学",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "西江大学2026年大学校庆，RIIZE下午场出演。",
    highlight: "西江大学校庆"
  },
  {
    id: 132,
    title: "崇实大学校庆 2026",
    type: "festival",
    typeLabel: "校庆",
    date: "2026-05-14",
    time: "17:30",
    city: "首尔",
    venue: "崇实大学",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费入场",
    ticketTime: "免费入场",
    organizer: "崇实大学",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "崇实大学2026年大学校庆，RIIZE同一天第二场校庆演出。",
    highlight: "崇实大学校庆"
  },
  {
    id: 133,
    title: "RIIZE 迷你二辑《II》日本线下活动 大阪场",
    type: "fansign",
    typeLabel: "签售会",
    date: "2026-07-22",
    time: "以官方为准",
    city: "大阪",
    venue: "大阪府内某所",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "应募抽选",
    ticketTime: "应募期间：6月17日起",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/20260617/",
    desc: "迷你二辑《II》日本应募抽选特典线下活动（大阪场）。",
    highlight: "日本线下活动 大阪"
  },
  {
    id: 134,
    title: "RIIZE 迷你二辑《II》日本线下活动 东京场",
    type: "fansign",
    typeLabel: "签售会",
    date: "2026-08-12",
    time: "以官方为准",
    city: "东京",
    venue: "东京都内某所",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "应募抽选",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "应募抽选",
    ticketTime: "应募期间：6月17日起",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/20260617/",
    desc: "迷你二辑《II》日本应募抽选特典线下活动（东京场）。",
    highlight: "日本线下活动 东京"
  },
  {
    id: 135,
    title: "M Countdown 《Do your dance》初舞台",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-06-18",
    time: "18:00",
    city: "首尔",
    venue: "Mnet",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "Mnet",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》主打曲《Do your dance》初舞台，M Countdown回归首秀。",
    highlight: "回归初舞台！"
  },
  {
    id: 136,
    title: "音乐银行 《Do your dance》舞台",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-06-19",
    time: "17:50",
    city: "首尔",
    venue: "KBS",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "KBS",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》音乐银行舞台。",
    highlight: "音乐银行"
  },
  {
    id: 137,
    title: "音乐中心 《Do your dance》舞台",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-06-20",
    time: "15:30",
    city: "首尔",
    venue: "MBC",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "MBC",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》音乐中心舞台。",
    highlight: "音乐中心"
  },
  {
    id: 138,
    title: "人气歌谣 《Do your dance》舞台",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-06-21",
    time: "15:40",
    city: "首尔",
    venue: "SBS",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "SBS",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》人气歌谣舞台。",
    highlight: "人气歌谣"
  },
  {
    id: 139,
    title: "Show Champion 《Do your dance》一位",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-06-24",
    time: "19:00",
    city: "首尔",
    venue: "MBC M",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "MBC M",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Show Champion舞台，获得回归首个一位！",
    highlight: "首个一位！🏆"
  },
  {
    id: 140,
    title: "M Countdown 《Do your dance》舞台",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-06-25",
    time: "18:00",
    city: "首尔",
    venue: "Mnet",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "Mnet",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》M Countdown第二周舞台。",
    highlight: "M Countdown"
  },
  {
    id: 141,
    title: "音乐银行 《Do your dance》一位",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-06-26",
    time: "17:50",
    city: "首尔",
    venue: "KBS",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "KBS",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》音乐银行一位，以15,059分打破2026年音乐银行最高分数纪录！",
    highlight: "第二个一位！破纪录🏆"
  },
  {
    id: 142,
    title: "音乐中心 《Do your dance》舞台",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-06-27",
    time: "15:30",
    city: "首尔",
    venue: "MBC",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "MBC",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》音乐中心第二周舞台。",
    highlight: "音乐中心"
  },
  {
    id: 143,
    title: "人气歌谣 《Do your dance》一位",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-06-28",
    time: "15:40",
    city: "首尔",
    venue: "SBS",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "SBS",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》人气歌谣一位，达成音乐节目三冠王！",
    highlight: "三冠王！🏆×3"
  },
  {
    id: 144,
    title: "M Countdown 《Do your dance》舞台",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-07-02",
    time: "18:00",
    city: "首尔",
    venue: "Mnet",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "Mnet",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》M Countdown第三周舞台。",
    highlight: "M Countdown"
  },
  {
    id: 145,
    title: "音乐银行 《Do your dance》舞台",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-07-03",
    time: "17:50",
    city: "首尔",
    venue: "KBS",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "KBS",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》音乐银行第三周舞台。",
    highlight: "音乐银行"
  },
  {
    id: 146,
    title: "音乐中心 《Do your dance》舞台",
    type: "festival",
    typeLabel: "打歌舞台",
    date: "2026-07-04",
    time: "15:30",
    city: "首尔",
    venue: "MBC",
    status: "ended",
    statusLabel: "已结束",
    price: "免费",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费观看",
    ticketTime: "免费观看",
    organizer: "MBC",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》音乐中心第三周舞台。",
    highlight: "音乐中心"
  },
  {
    id: 147,
    title: "RIIZE 日本2nd Single「All of You」Showcase",
    type: "fanmeeting",
    typeLabel: "Showcase",
    date: "2026-02-18",
    time: "以官方为准",
    city: "东京",
    venue: "东京都内某所",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "应募抽选",
    ticketTime: "应募期间：2025年12月起",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/2026012902/",
    desc: "日本第二张单曲《All of You》发售纪念Showcase。",
    highlight: "日本2单Showcase"
  },
  {
    id: 148,
    title: "RIIZE 日本2nd Single「All of You」Premium Group签名会",
    type: "fansign",
    typeLabel: "签售会",
    date: "2026-02-18",
    time: "傍晚以后",
    city: "东京",
    venue: "东京都内某所",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "应募抽选",
    ticketTime: "应募期间：2025年12月起",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/2026012902/",
    desc: "日本第二张单曲《All of You》Premium Group签名会，当选100名。",
    highlight: "日本2单签名会"
  },
  {
    id: 149,
    title: "RIIZE 日本3rd Single「Sunburst」Showcase 大阪",
    type: "fanmeeting",
    typeLabel: "Showcase",
    date: "2026-08-26",
    time: "以官方为准",
    city: "大阪",
    venue: "大阪府内某所",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "应募抽选",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "应募抽选",
    ticketTime: "应募期间：7月27日起",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "日本第三张单曲《Sunburst》预约者对象Showcase（大阪场）。",
    highlight: "日本3单Showcase 大阪"
  },
  {
    id: 150,
    title: "迷你二辑《II》Makestar 线上签售会",
    type: "fansign",
    typeLabel: "线上签售",
    date: "2026-06-22",
    time: "以官方为准",
    city: "线上",
    venue: "线上",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Makestar",
    ticketTime: "应募期间：6月15日-6月18日",
    organizer: "Makestar",
    ticketUrl: "https://www.makestar.co.kr/",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Makestar平台线上视频签售会。",
    highlight: "Makestar 线上签售"
  },
  {
    id: 151,
    title: "迷你二辑《II》Withmuu 线上签售会",
    type: "fansign",
    typeLabel: "线上签售",
    date: "2026-06-23",
    time: "以官方为准",
    city: "线上",
    venue: "线上",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Withmuu",
    ticketTime: "应募期间：6月15日-6月19日",
    organizer: "Withmuu",
    ticketUrl: "https://www.withmuu.com/",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Withmuu平台线上视频签售会。",
    highlight: "Withmuu 线上签售"
  },
  {
    id: 152,
    title: "迷你二辑《II》Ktown4u 线上签售会",
    type: "fansign",
    typeLabel: "线上签售",
    date: "2026-06-25",
    time: "以官方为准",
    city: "线上",
    venue: "线上",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Ktown4u",
    ticketTime: "应募期间：6月15日-6月20日",
    organizer: "Ktown4u",
    ticketUrl: "https://www.ktown4u.com/",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Ktown4u平台线上视频签售会。",
    highlight: "Ktown4u 线上签售"
  },
  {
    id: 153,
    title: "迷你二辑《II》Soundwave 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-06-28",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Soundwave",
    ticketTime: "应募期间：6月15日-6月21日",
    organizer: "Soundwave",
    ticketUrl: "https://www.soundwave.co.kr/",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Soundwave平台线下签售会。",
    highlight: "Soundwave 线下签售"
  },
  {
    id: 154,
    title: "迷你二辑《II》Everline 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-06-29",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Everline",
    ticketTime: "应募期间：6月15日-6月22日",
    organizer: "Everline",
    ticketUrl: "https://www.everline.kr/",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Everline平台线下签售会。",
    highlight: "Everline 线下签售"
  },
  {
    id: 155,
    title: "迷你二辑《II》Weverse Shop 线上签售会",
    type: "fansign",
    typeLabel: "线上签售",
    date: "2026-07-01",
    time: "以官方为准",
    city: "线上",
    venue: "线上",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Weverse Shop",
    ticketTime: "应募期间：6月15日-6月25日",
    organizer: "Weverse",
    ticketUrl: "https://www.weverseshop.io/",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Weverse Shop平台线上视频签售会。",
    highlight: "Weverse 线上签售"
  },
  {
    id: 156,
    title: "迷你二辑《II》Apple Music 线上签售会",
    type: "fansign",
    typeLabel: "线上签售",
    date: "2026-07-02",
    time: "以官方为准",
    city: "线上",
    venue: "线上",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Apple Music",
    ticketTime: "应募期间：6月15日-6月26日",
    organizer: "Apple Music",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Apple Music平台线上视频签售会。",
    highlight: "Apple Music 线上签售"
  },
  {
    id: 157,
    title: "迷你二辑《II》Music Korea 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-07-03",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Music Korea",
    ticketTime: "应募期间：6月15日-6月27日",
    organizer: "Music Korea",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Music Korea平台线下签售会。",
    highlight: "Music Korea 线下签售"
  },
  {
    id: 158,
    title: "迷你二辑《II》Music Plant 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-07-04",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Music Plant",
    ticketTime: "应募期间：6月15日-6月28日",
    organizer: "Music Plant",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Music Plant平台线下签售会。",
    highlight: "Music Plant 线下签售"
  },
  {
    id: 159,
    title: "迷你二辑《II》Namil Music 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-07-05",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Namil Music",
    ticketTime: "应募期间：6月15日-6月29日",
    organizer: "Namil Music",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Namil Music平台线下签售会。",
    highlight: "Namil Music 线下签售"
  },
  {
    id: 160,
    title: "RIIZE 日本3rd Single「Sunburst」幸运抽选签名会",
    type: "fansign",
    typeLabel: "签售会",
    date: "2026-09-01",
    time: "以官方为准",
    city: "东京",
    venue: "东京都内某所",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "应募抽选",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "应募抽选",
    ticketTime: "应募期间：7月27日起",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "日本第三张单曲《Sunburst》幸运抽选签名会。",
    highlight: "日本3单签名会"
  },
  {
    id: 161,
    title: "SBS 歌谣大战 Summer 2026",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-07-09",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "以官方公告为准",
    organizer: "SBS",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "SBS 歌谣大战 Summer 2026，RIIZE出演。",
    highlight: "SBS歌谣大战 Summer"
  },
  {
    id: 162,
    title: "迷你二辑《II》Yes24 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-07-06",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Yes24",
    ticketTime: "应募期间：6月15日-6月30日",
    organizer: "Yes24",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Yes24平台线下签售会。",
    highlight: "Yes24 线下签售"
  },
  {
    id: 163,
    title: "迷你二辑《II》Aladin 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-07-07",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Aladin",
    ticketTime: "应募期间：6月15日-7月1日",
    organizer: "Aladin",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Aladin平台线下签售会。",
    highlight: "Aladin 线下签售"
  },
  {
    id: 164,
    title: "迷你二辑《II》Synnara 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-07-08",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Synnara",
    ticketTime: "应募期间：6月15日-7月2日",
    organizer: "Synnara",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Synnara平台线下签售会。",
    highlight: "Synnara 线下签售"
  },
  {
    id: 165,
    title: "迷你二辑《II》Hot Tracks 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-07-09",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Hot Tracks",
    ticketTime: "应募期间：6月15日-7月3日",
    organizer: "Hot Tracks",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Hot Tracks平台线下签售会。",
    highlight: "Hot Tracks 线下签售"
  },
  {
    id: 166,
    title: "RIIZE 出道3周年 生日派对",
    type: "fanmeeting",
    typeLabel: "生日会",
    date: "2026-09-04",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出道3周年纪念生日派对活动。",
    highlight: "3周年生日派对！"
  },
  {
    id: 167,
    title: "RIIZE 官方粉丝俱乐部 BRIIZE 会员日",
    type: "fanmeeting",
    typeLabel: "FC活动",
    date: "2026-08-17",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "会员限定",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Weverse",
    ticketTime: "会员先行",
    organizer: "SM Entertainment",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 官方粉丝俱乐部 BRIIZE 会员日活动。",
    highlight: "BRIIZE会员日"
  },
  {
    id: 168,
    title: "迷你二辑《II》Interpark 线下签售会",
    type: "fansign",
    typeLabel: "线下签售",
    date: "2026-07-10",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "应募抽选",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "Interpark",
    ticketTime: "应募期间：6月15日-7月4日",
    organizer: "Interpark",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "迷你二辑《II》Interpark平台线下签售会。",
    highlight: "Interpark 线下签售"
  },
  {
    id: 169,
    title: "认识的哥哥 录制",
    type: "festival",
    typeLabel: "综艺录制",
    date: "2026-06-16",
    time: "以官方为准",
    city: "首尔",
    venue: "JTBC",
    status: "ended",
    statusLabel: "已结束",
    price: "观众申请",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "JTBC观众申请",
    ticketTime: "以官方为准",
    organizer: "JTBC",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出演JTBC《认识的哥哥》节目录制。",
    highlight: "认识的哥哥"
  },
  {
    id: 170,
    title: "一周的偶像 录制",
    type: "festival",
    typeLabel: "综艺录制",
    date: "2026-06-17",
    time: "以官方为准",
    city: "首尔",
    venue: "MBC",
    status: "ended",
    statusLabel: "已结束",
    price: "观众申请",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "MBC观众申请",
    ticketTime: "以官方为准",
    organizer: "MBC",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出演MBC《一周的偶像》节目录制。",
    highlight: "一周的偶像"
  },
  {
    id: 171,
    title: "RIIZE x EITHER& 联名快闪店",
    type: "popup",
    typeLabel: "快闪店",
    date: "2026-05-09",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "免费入场",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "免费入场",
    ticketTime: "免费入场",
    organizer: "EITHER&",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE x EITHER& 联名快闪店，成灿、元彬相关。",
    highlight: "EITHER&联名快闪"
  },
  {
    id: 172,
    title: "RIIZE 出道3周年 纪念展览",
    type: "popup",
    typeLabel: "展览",
    date: "2026-09-01",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "以官方公告为准",
    organizer: "SM Entertainment",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "RIIZE 出道3周年纪念展览活动。",
    highlight: "3周年纪念展览"
  },
  {
    id: 173,
    title: "RIIZE JAPAN FANMEETING 2026 RPG 追加公演",
    type: "fanmeeting",
    typeLabel: "见面会",
    date: "2026-07-25",
    time: "以官方为准",
    city: "东京",
    venue: "以官方公告为准",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "JPY",
    priceCNY: "",
    ticketPlatform: "e+ / ぴあ / 罗森票务",
    ticketTime: "以官方公告为准",
    organizer: "SM Entertainment Japan",
    ticketUrl: "https://riizeofficial.jp/",
    noticeUrl: "https://riizeofficial.jp/news/",
    desc: "RIIZE 日本粉丝见面会 2026 RPG 追加公演。",
    highlight: "日本FM追加公演"
  },
  {
    id: 174,
    title: "2026 首尔歌谣大赏",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-01-15",
    time: "以官方为准",
    city: "首尔",
    venue: "高尺天空巨蛋",
    status: "ended",
    statusLabel: "已结束",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "以官方公告为准",
    organizer: "首尔体育",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "第36届首尔歌谣大赏，RIIZE出演。",
    highlight: "首尔歌谣大赏"
  },
  {
    id: 175,
    title: "2026 Melon Music Awards",
    type: "festival",
    typeLabel: "颁奖礼",
    date: "2026-12-01",
    time: "以官方为准",
    city: "首尔",
    venue: "以官方公告为准",
    status: "upcoming",
    statusLabel: "即将开始",
    price: "以官方为准",
    currency: "KRW",
    priceCNY: "",
    ticketPlatform: "以官方公告为准",
    ticketTime: "以官方公告为准",
    organizer: "Kakao",
    ticketUrl: "",
    noticeUrl: "https://weverse.io/riize/notice",
    desc: "2026 Melon Music Awards，RIIZE提名/出演。",
    highlight: "MMA 2026"
  }
];
